apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: frankdesantes/{{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.name }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        livenessProbe:
           httpGet:
             path: /healthz
             port: {{ .Values.livenessProbe.port }}
        readinessProbe:
           httpGet:
             path: /healthz
             port: {{ .Values.readinessProbe.port }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

